name: Build LineageOS for A30

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      USE_CCACHE: 1
      CCACHE_DIR: ${{ runner.temp }}/ccache

    steps:
      - name: Checkout LineageOS source
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android
          token: ${{ secrets.GITHUB_TOKEN }}
          path: rom

      - name: Checkout device tree
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_device_samsung_a30
          token: ${{ secrets.GITHUB_TOKEN }}
          path: rom/device/samsung/a30

      - name: Checkout vendor tree
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_vendor_samsung_exynos7885
          token: ${{ secrets.GITHUB_TOKEN }}
          path: rom/vendor/samsung/exynos7885

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex git gnupg gperf imagemagick \
            lib32ncurses5-dev lib32z1-dev libc6-dev-i386 libgl1-mesa-dev liblz4-tool libncurses5-dev \
            libssl-dev lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev ccache openjdk-11-jdk

      - name: Setup build environment
        run: |
          cd rom
          source build/envsetup.sh
          lunch lineage_a30-userdebug

      - name: Build LineageOS
        run: |
          cd rom
          mka bacon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lineageos_a30_build
          path: rom/out/target/product/a30/*.zip
