name: Build TWRP Recovery for Galaxy A30 with Custom Version

on:
  push:
    branches:
      - main

jobs:
  build-twrp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex git libssl-dev libncurses5-dev unzip zip repo

      - name: Initialize repo manifest
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j4

      - name: Set custom TWRP version
        run: |
          sed -i 's/^TW_DEVICE_VERSION :=.*$/TW_DEVICE_VERSION := 3.7.0-12.1Orbit/' device/samsung/a30/BoardConfig.mk || echo 'TW_DEVICE_VERSION := 3.7.0-12.1Orbit' >> device/samsung/a30/BoardConfig.mk

      - name: Setup build environment
        run: |
          . build/envsetup.sh
          lunch twrp_a30-eng

      - name: Build recovery image
        run: |
          make recoveryimage -j$(nproc)

      - name: Upload recovery image artifact
        uses: actions/upload-artifact@v3
        with:
          name: twrp_recovery_image
          path: out/target/product/a30/recovery.img
