name: Build LineageOS A30 Minimal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod +x repo
        sudo mv repo /usr/local/bin/

    - name: Initialize and sync repo
      run: |
        repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
        repo sync -c -j4 --force-sync

    - name: Clone trees
      run: |
        git clone https://github.com/crazo7924/device_samsung_a30 device/samsung/a30
        git clone https://github.com/EurekaDevelopment/Eureka-Kernel-Exynos7885 kernel/samsung/a30
        git clone https://github.com/LineageOS/android_vendor_samsung_a30 vendor/samsung/a30

    - name: Setup build env
      run: |
        source build/envsetup.sh
        lunch lineage_a30-userdebug

    - name: Build ROM
      run: mka bacon -j4
