name: Build NusantaraOS for A30

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev libc6-dev-i386 libgl1-mesa-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev ccache

    - name: Setup repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Sync ROM source
      run: |
        repo init -u https://github.com/NusantaraOS/manifest.git -b lineage-20
        repo sync --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

    - name: Clone device, kernel, vendor trees
      run: |
        git clone https://github.com/crazo7924/device_samsung_a30 device/samsung/a30lte
        git clone https://github.com/EurekaDevelopment/Eureka-Kernel-Exynos7885 kernel/samsung/exynos7904
        git clone <vendor_repo_link> vendor/samsung/a30lte

    - name: Build ROM
      run: |
        source build/envsetup.sh
        lunch a30lte-userdebug
        mka bacon -j$(nproc --all)

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: NusantaraOS-A30
        path: out/target/product/a30lte/*.zip
