name: OrangeFox Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: 🧽 Prepare environment
      run: |
        apt update && apt install -y \
        git wget curl unzip bc bison build-essential \
        ccache curl flex g++-multilib gcc-multilib \
        gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2 libxml2-utils lzop openjdk-8-jdk \
        pngcrush rsync schedtool squashfs-tools \
        xsltproc zip zlib1g-dev

    - name: 🧬 Clone OrangeFox source
      run: |
        mkdir -p ~/orangefox && cd ~/orangefox
        repo init -u https://gitlab.com/OrangeFox/sync.git -b fox_11.0
        git clone https://github.com/RaminDroid/local_manifest.git .repo/local_manifests
        repo sync -j$(nproc --all)

    - name: 🔨 Build Recovery
      run: |
        cd ~/orangefox
        . build/envsetup.sh
        lunch omni_a30-eng
        mka recoveryimage

    - name: 📤 Upload recovery
      uses: actions/upload-artifact@v3
      with:
        name: OrangeFox-A30
        path: ~/orangefox/out/target/product/a30/recovery.img
