
- name: Free up space
  run: |
    echo "Cleaning unnecessary files to free up disk space..."
    sudo rm -rf /usr/share/dotnet
    sudo rm -rf /opt/ghc
    sudo rm -rf /usr/local/lib/android
    sudo apt-get autoremove -y
    sudo apt-get clean
    df -h
